name = "lean-formalisation"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Reduce", "DCE", "IncrementalFixpoint", "ReactiveRel"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "Reduce"

[[lean_lib]]
name = "DCE"

[[lean_lib]]
name = "IncrementalFixpoint"

[[lean_lib]]
name = "ReactiveRel"
